### ISSUE TITLE
How to reproduce the analysis with data (hdf5 file format) from H. Chang et al., Molecular Cell, 2018 ?

### ISSUE THREAD

**Issue by Tsinghua-gongjing** [hyeshik/tailseeker#13]
Dear Hyeshik,

Thank you for the beautiful software. The manuals are pretty completed. I noticed that you have published a paper (Terminal Uridylyltransferases Execute Programmed Clearance of Maternal Transcriptome in Vertebrate Embryos) on Molecular Cell this year. The related data are deposited at Zenodo (https://zenodo.org/record/1049284#.WxffLVOFO3A). 

I have downloaded all the tail-seq data (11 parts), unzip and concatenate the files. Then I got the combined hdf5 file, which is hierarchy while loaded into Python:

`>>> import h5py`

`>>> f = h5py.File("TUT-tailseq/hs25.h5.xz.partall", 'r')`

`>>> f.keys()`

`[u'hs25']`

`>>> f['hs25'].keys()`

`[u'e00', u'e01', u'e02', u'e04', u'e06', u'e08', u'spk118', u'spk128', u'spk16', u'spk32', u'spk64', u'spk8', u'spkN']`

`>>> f['hs25']['e00'].keys()`

`[u'basecalls', u'intensities']`

`>>> f['hs25']['e00']['basecalls'].keys()`

`[u'1_1101', u'1_1102', u'1_1103', u'1_1104', u'1_1105', u'1_1106', u'1_1107', u'1_1108', u'1_1109', u'1_1110', u'1_1111', u'1_1112', u'1_1113', u'1_1114', u'1_1115', u'1_1116', u'1_1201', u'1_1202', u'1_1203', u'1_1204', u'1_1205', u'1_1206', u'1_1207', u'1_1208', u'1_1209', u'1_1210', u'1_1211', u'1_1212', u'1_1213', u'1_1214', u'1_1215', u'1_1216', u'1_2101', u'1_2102', u'1_2103', u'1_2104', u'1_2105', u'1_2106', u'1_2107', u'1_2108', u'1_2109', u'1_2110', u'1_2111', u'1_2112', u'1_2113', u'1_2114', u'1_2115', u'1_2116', u'1_2201', u'1_2202', u'1_2203', u'1_2204', u'1_2205', u'1_2206', u'1_2207', u'1_2208', u'1_2209', u'1_2210', u'1_2211', u'1_2212', u'1_2213', u'1_2214', u'1_2215', u'1_2216', u'2_1101', u'2_1102', u'2_1103', u'2_1104', u'2_1105', u'2_1106', u'2_1107', u'2_1108', u'2_1109', u'2_1110', u'2_1111', u'2_1112', u'2_1113', u'2_1114', u'2_1115', u'2_1116', u'2_1201', u'2_1202', u'2_1203', u'2_1204', u'2_1205', u'2_1206', u'2_1207', u'2_1208', u'2_1209', u'2_1210', u'2_1211', u'2_1212', u'2_1213', u'2_1214', u'2_1215', u'2_1216', u'2_2101', u'2_2102', u'2_2103', u'2_2104', u'2_2105', u'2_2106', u'2_2107', u'2_2108', u'2_2109', u'2_2110', u'2_2111', u'2_2112', u'2_2113', u'2_2114', u'2_2115', u'2_2116', u'2_2201', u'2_2202', u'2_2203', u'2_2204', u'2_2205', u'2_2206', u'2_2207', u'2_2208', u'2_2209', u'2_2210', u'2_2211', u'2_2212', u'2_2213', u'2_2214', u'2_2215', u'2_2216']`

My question is **how to convert the hdf5 file into a normal directory eactly same as full output hierarchy from MiSeq or HiSeq?** Therefore I can run tailseeker. Or is there any links where I can access the analysis results of the paper?

I'm new to this filed, any suggestion/link is appreciated.

Thanks,
Jing

**Comment by hyeshik** [comment]
Hello Jing,

Thank you for reading our paper with interests. Tailseeker does not currently support HDF5-formatted dataset. We had to create an alternative compact raw data format contained in HDF5 to remove the reads from samples sequenced in the flow cell together but are not related to the paper. However, as we had done analyses already with the original full CIF data, we could not have enough time to add support for the new data format in tailseeker.

I uploaded the processed data upon your request to [Dropbox](https://www.dropbox.com/s/n501i9y4v041i64/hs25-tailhist.tar.xz?dl=0). Please find the msgpack files in the archive, containing 3D histograms consists of values representing read counts in the space with gene id (0th dim), polyA length (1st dim), U tail length (2st dim). They can be loaded with the `pandas.read_msgpack` function.

Please let me know if there's anything I can help you more.

Thank you!
Hyeshik
