### ISSUE TITLE
Saving CIF-files from MiSeq for tailseeker?

### ISSUE THREAD

**Issue by fsalmen84** [hyeshik/tailseeker#14]
Hi,

I've tried to obtain the CIF-files from a MiSeq run to be able to run tailseeker. I've followed the instructions I've found online which is also what Illumina says (changing two lines in two different files before staring the run):

"Saving cif files on a MiSeq has been shown to be possible by some of our customers with older versions of the MCS/RTA software, but I must stress that this is not supported by Illumina in any way.
In the case that the customer was able to save cif files, these were the only changes that the customer made:
In the C:\Illumina\RTA\Configs\MiSeq.Configuration.xml file.
SaveIntensityMaps>true</SaveIntensityMaps
and in the MiSeqControlSoftware.Options.cfg in D:\Illumina\Miseq Control Software
CopyIntensityFilesToNetwork>true</CopyIntensityFilesToNetwork
After making these two changes the CIF files were saved in the Run Folder under the cycle directories in [RunFolder]/Data/Intensities/Lane#/CX.1
I must warn you that our product engineers have warned that the MiSeq was not designed to save Cif files and as a consequence might run out of local disc space if this is done. Saving Cif files has not been internally tested on the MiSeq, so we can't offer any additional advice or guarantee that this will work."

However, no files were saved in my runfolder (or anywhere), do you know what other changes that needs to be done? Maybe this is only possible with some versions of MCS/RTA software as they say?

I also found these two lines which might have something to do with it:
"CopyIntensities>false</CopyIntensities
DeleteIntensitiesAfterProcessing>true</DeleteIntensitiesAfterProcessing"

Best regards!
Fredrik

**Comment by hyeshik** [comment]
Hi Fredrik,

We only modified those two lines as mentioned in the message you quoted. With the MiSeq of our lab, the MCS has been producing CIF files without a problem until now with MCS version 2.6.2.1. Please give it a try for further modifications you're suspecting that might be related to CIF files. Or, you may contact a local Illumina service provider. Unfortunately, our domestic representatives did not want to tell us anything about CIF files at all.

Hyeshik
