### ISSUE TITLE
Job submission not allowed

### ISSUE THREAD

**Issue by gk7279** [hyeshik/tailseeker#3]
Hi hyeshik,

Here is my command

`/user/work/bin/tailseeker-master/bin/tseek run -c sbatch  -j 16`

But I get the following error
### 

Error executing jobscript (exit code 1):
[TACC]: Job submission is not allowed from this host. Please submit
[TACC]: through one of the available login resources.
### 

When I spoke with our cluster admins, they informed me that I have to run the submission command by standing on a login node and not on a computing node. Any idea on how to tweak around this?

Thanks in advance.

**Comment by ac-simpson** [comment]
Hi, did you ever solve this issue? I am having the same problem with TACC (for a totally different workflow)
