### ISSUE TITLE
Batch script is empty

### ISSUE THREAD

**Issue by gk7279** [hyeshik/tailseeker#4]
I was able to run the scripts via the cluster. However, I see this below erros

**sbatch: error: Batch script is empty!
/home/work/bin/AYB2-master/bin/AYB: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory
Error in job basecall_ayb while creating output file scratch/aybcalls/R5_a1112.fastq.gz.
RuleException:
CalledProcessError in line 156 of /home/work/bin/tailseeker-master/tailseeker/main.py:
Command '/home/work/bin/AYB2-master/bin/AYB -p 32 -o /scratch/AMFAE_8samples/scratch/aybcalls/R5_a1112 -i /scratch/AMFAE_8samples                 -b R51 -f fastq.gz -r L1T1112' returned non-zero exit status 127
  File "/home/work/bin/tailseeker-master/tailseeker/main.py", line 156, in __rule_basecall_ayb
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
rule basecall_ayb:
    output: scratch/aybcalls/R5_a2101.fastq.gz
    wildcards: tile=a2101, read=R5
    threads: 32
Pseudo-terminal will not be allocated because stdin is not a terminal.**

But when I try running this individually - /home/work/bin/AYB2-master/bin/AYB
I see it running smoothly without throwing any errors?

Thanks

**Comment by hyeshik** [comment]
In the error message, rtld shows a warning that it failed to load libblas.so.3. You will need to compile AYB again with the library version that your worker nodes have. Alternatively, you may also try compiling AYB statically.

**Comment by hyeshik** [comment]
In the error message, rtld shows a warning that it failed to load libblas.so.3. You will need to compile AYB again with the library version that your worker nodes have. Alternatively, you may also try compiling AYB statically.
