### ISSUE TITLE
Error in job merge_and_deduplicate_taginfo

### ISSUE THREAD

**Issue by gk7279** [hyeshik/tailseeker#5]
Hi Hyeshik,

I was able to rectify the earlier solution.
But the job runs in success partially and encounters the below message....
Can you please comment?
###### 

Error in job merge_and_deduplicate_taginfo while creating output file taginfo/WT_ZT12.txt.gz.
RuleException:
CalledProcessError in line 220 of 
/home/work/bin/tailseeker-master/tailseeker/main.py:
Command 'zcat scratch/taginfo/WT_ZT12_a1101.txt.gz scratch/taginfo/WT_ZT12_a1102.txt.gz scratch/taginfo/WT_ZT12_a1103.txt.gz scratch/taginfo/WT_ZT12_a1104.txt.gz scratch/taginfo/WT_ZT12_a1105.txt.gz scratch/taginfo/WT_ZT12_a1106.txt.gz scratch/taginfo/WT_ZT12_a1107.txt.gz scratch/taginfo/WT_ZT12_a1108.txt.gz scratch/taginfo/WT_ZT12_a1109.txt.gz scratch/taginfo/WT_ZT12_a1110.txt.gz scratch/taginfo/WT_ZT12_a1111.txt.gz scratch/taginfo/WT_ZT12_a1112.txt.gz scratch/taginfo/WT_ZT12_a1113.txt.gz scratch/taginfo/WT_ZT12_a1114.txt.gz scratch/taginfo/WT_ZT12_a2101.txt.gz scratch/taginfo/WT_ZT12_a2102.txt.gz scratch/taginfo/WT_ZT12_a2103.txt.gz scratch/taginfo/WT_ZT12_a2104.txt.gz scratch/taginfo/WT_ZT12_a2105.txt.gz scratch/taginfo/WT_ZT12_a2106.txt.gz scratch/taginfo/WT_ZT12_a2107.txt.gz scratch/taginfo/WT_ZT12_a2108.txt.gz scratch/taginfo/WT_ZT12_a2109.txt.gz scratch/taginfo/WT_ZT12_a2110.txt.gz scratch/taginfo/WT_ZT12_a2111.txt.gz scratch/taginfo/WT_ZT12_a2112.txt.gz scratch/taginfo/WT_ZT12_a2113.txt.gz scratch/taginfo/WT_ZT12_a2114.txt.gz |                 env BGZIP_OPT="-@ 12" sort -t " " -k6,6 -k1,1 -k2,2n                     --compress-program=/home/work/bin/tailseeker-master/bin/bgzip-wrap --parallel=12 |                 /home/work/bin/tailseeker-master/bin/tailseq-dedup-perfect |                 env BGZIP_OPT="-@ 12" sort -t "    " -k1,1 -k2,2n                     --compress-program=/home/work/bin/tailseeker-master/bin/bgzip-wrap --parallel=12 |                 /home/work/bin/htslib-1.3.1/bin/bgzip -@ 12 -c > taginfo/WT_ZT12.txt.gz' returned non-zero exit status 2
  File "/home/work/bin/tailseeker-master/tailseeker/main.py", line 220, in __rule_merge_and_deduplicate_taginfo
Removing output files of failed job merge_and_deduplicate_taginfo since they might be corrupted:
taginfo/WT_ZT12.txt.gz
Will exit after finishing currently running jobs.
###### 

Thank you

**Comment by hyeshik** [comment]
Hi Gokhul,

The error message has limited information how the job is terminated. There are many possible situations that leads those errors. Insufficient free space on /tmp or /var/tmp can be one of them. Can you run the command step-by-step by breaking those pipelined sentences into separate commands, and observe where an error is occurred? For e.g.,
1.  zcat scratch/........gz > output1
2. cat output1 | env BGZIP_OPT="-@ 12" sort -t " " -k6,6 -k1,1 -k2,2n --compress-program=/home/work/bin/tailseeker-master/bin/bgzip-wrap --parallel=12 > output2
3. cat output2 | /home/work/bin/tailseeker-master/bin/tailseq-dedup-perfect > output3
4. cat output3 | env BGZIP_OPT="-@ 12" sort -t " " -k1,1 -k2,2n --compress-program=/home/work/bin/tailseeker-master/bin/bgzip-wrap --parallel=12 > output4
5. cat output4 | /home/work/bin/htslib-1.3.1/bin/bgzip -@ 12 -c > output5

**Comment by tvincent07** [comment]
Hi, 
I have quite the same problem, so I separated the commands as you said and the error is on the third point. I have a seg fault...
```
 58 Segmentation fault      | /opt/tailseeker/bin/tailseq-dedup-perfect scratch/stats/perfdup-traces-e15.txt.gz > tmp3.out
Error in job merge_and_deduplicate_taginfo while creating output files taginfo/e15.txt.gz, scratch/stats/perfdup-traces-e15.txt.gz.
RuleException:
CalledProcessError in line 301 of /opt/tailseeker/tailseeker/main.py:
Command 'zcat scratch/taginfo-fl-r02/e15_a1101.txt.gz scratch/taginfo-fl-r02/e15_a1102.txt.gz scratch/taginfo-fl-r02/e15_a1103.txt.gz scratch/taginfo-fl-r02/e15_a1104.txt.gz scratch/taginfo-fl-r02/e15_a1105.txt.gz scratch/taginfo-fl-r02/e15_a1106.txt.gz scratch/taginfo-fl-r02/e15_a1107.txt.gz scratch/taginfo-fl-r02/e15_a1108.txt.gz scratch/taginfo-fl-r02/e15_a1109.txt.gz scratch/taginfo-fl-r02/e15_a1110.txt.gz scratch/taginfo-fl-r02/e15_a1111.txt.gz scratch/taginfo-fl-r02/e15_a1112.txt.gz scratch/taginfo-fl-r02/e15_a1113.txt.gz scratch/taginfo-fl-r02/e15_a1114.txt.gz scratch/taginfo-fl-r02/e15_a1115.txt.gz scratch/taginfo-fl-r02/e15_a1116.txt.gz scratch/taginfo-fl-r02/e15_a1117.txt.gz scratch/taginfo-fl-r02/e15_a1118.txt.gz scratch/taginfo-fl-r02/e15_a1119.txt.gz scratch/taginfo-fl-r02/e15_a2101.txt.gz scratch/taginfo-fl-r02/e15_a2102.txt.gz scratch/taginfo-fl-r02/e15_a2103.txt.gz scratch/taginfo-fl-r02/e15_a2104.txt.gz scratch/taginfo-fl-r02/e15_a2105.txt.gz scratch/taginfo-fl-r02/e15_a2106.txt.gz scratch/taginfo-fl-r02/e15_a2107.txt.gz scratch/taginfo-fl-r02/e15_a2108.txt.gz scratch/taginfo-fl-r02/e15_a2109.txt.gz scratch/taginfo-fl-r02/e15_a2110.txt.gz scratch/taginfo-fl-r02/e15_a2111.txt.gz scratch/taginfo-fl-r02/e15_a2112.txt.gz scratch/taginfo-fl-r02/e15_a2113.txt.gz scratch/taginfo-fl-r02/e15_a2114.txt.gz scratch/taginfo-fl-r02/e15_a2115.txt.gz scratch/taginfo-fl-r02/e15_a2116.txt.gz scratch/taginfo-fl-r02/e15_a2117.txt.gz scratch/taginfo-fl-r02/e15_a2118.txt.gz scratch/taginfo-fl-r02/e15_a2119.txt.gz > tmp1.out; echo "cest bon 1";                cat tmp1.out | env BGZIP_OPT="-@ 1" sort -t "	" -k6,6 -k1,1 -k2,2n                     --compress-program=/opt/tailseeker/bin/bgzip-wrap --parallel=1 > tmp2.out; echo "cest bon 2";                cat tmp2.out |/opt/tailseeker/bin/tailseq-dedup-perfect scratch/stats/perfdup-traces-e15.txt.gz > tmp3.out; echo "cestbon 3";                 cat tmp3.out | env BGZIP_OPT="-@ 1" sort -t "	" -k1,1 -k2,2n                     --compress-program=/opt/tailseeker/bin/bgzip-wrap --parallel=1 > tmp4.out; echo "cest bon 4";                cat tmp4.out | /opt/tailseeker/bin/bgzip -@ 1 -c > taginfo/e15.txt.gz' returned non-zero exit status 139
  File "/opt/tailseeker/tailseeker/main.py", line 301, in __rule_merge_and_deduplicate_taginfo
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Exiting because a job execution failed. Look above for error message
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```
To be honest I don't really know how to fix it...
Thanks for your help. 
Timothée
