### ISSUE TITLE
Problem with Miseq-V3, docker latest version 

### ISSUE THREAD

**Issue by tvincent07** [hyeshik/tailseeker#6]
Hi, 
I try to run tailseeker on a slurm centos 6 cluster. 
I downloaded the latest docker version of tailseeker. 
I work with Arabidopsis thaliana so I use the level 1 of tailseeker. 
When I strictly follow the running procedure, I get the error : 

`Error response from daemon: cannot bind mount volume:  volume paths must be absolute.
`
So I changed the run sentence by removing $REFDBARGS. It appears that tailseeker started to run, but I quickly have the following error : 

```
ValueError in line 37 of /opt/tailseeker/tailseeker/main.py:
MiSeq-V3 is in the list of known sequencing chemistry.
  File "/opt/tailseeker/tailseeker/main.py", line 37, in <module>
  File "/opt/tailseeker/tailseeker/sequencers.py", line 58, in get_tiles
```

When I tried to install Tailseeker from source, I've been able to add the Miseq-V3 specification in `sequencers.py`, but then I get other error more difficult to solve, that's why I tried the docker version. 
Thanks

**Comment by hyeshik** [comment]
Hi,
Tailseeker does not support the MiSeq-V3 chemistry, yet. The status shall not change soon as my lab haven't tried the new version yet. You may try to circumvent the problem by just adding the list of tiles in tailseeker/sequencers.py. Sometimes, you need to tune some signal processing parameters and fix the raw file handing to make it run correctly.
