### ISSUE TITLE
Color matrix < ~Data/Intensities/BaseCalls/Matrix/s_1_3_1117_matrix.txt > could not be open 

### ISSUE THREAD

**Issue by tvincent07** [hyeshik/tailseeker#8]
Hi, 
i'm sorry to write another post but I resolved my last error post by adding 

`ENV PYTHONPATH /opt/tailseeker:$PYTHONPATH`
to the Dockerfile and by creating a new docker image. 
The thing is I quickly have another mistake more difficult to solve (for me) : 
```
Color matrix </home/tvincent/Helene/run1Miseq4/runMiseq1/160808_M03768_0018_000000000-AMUBW/Data/Intensities/BaseCalls/Matrix/s_1_3_1117_matrix.txt> could not be opened.
Error in job process_signals while creating output files scratch/sigproc-conf/a1117.ini, scratch/taginfo/e00_a1117.txt.gz, scratch/taginfo/e05_a1117.txt.gz, scratch/taginfo/e10_a1117.txt.gz, scratch/taginfo/e100_a1117.txt.gz, scratch/taginfo/e105_a1117.txt.gz, scratch/taginfo/e110_a1117.txt.gz, 
```
etc, the list is long.

```
scratch/signals/spk64_a1117.sigpack, scratch/signals/spk8_a1117.sigpack, scratch/signals/spkN_a1117.sigpack, scratch/stats/signal-proc-a1117.csv.
RuleException:
CalledProcessError in line 200 of /opt/tailseeker/tailseeker/main.py:
Command '/opt/tailseeker/bin/tailseq-import scratch/sigproc-conf/a1117.ini' returned non-zero exit status 255
  File "/opt/tailseeker/tailseeker/main.py", line 200, in __rule_process_signals
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Exiting because a job execution failed. Look above for error message
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```

I checked and the matrix file location is the good one. I don't understand why it cannot be open. 
Thanks for replying me. 
best
Timothée

**Comment by hyeshik** [comment]
The matrix file holds a 4x4 array for the fluorescence signal deconvolution. Since Illumina does not officially guarantee the consistent data layout of internal files, we need to fix the program whenever Illumina changes the internals. I guess they removed the file or moved to somewhere else than the original location for MiSeq V3. You'll need to find the new location of color matrices and change the related codes in tailseeker to adapt to the changes.

**Comment by hyeshik** [comment]
The location of data must be accessible from the Docker container. With the default wrapper script, the data files are exposed as `/data`.

**Comment by tvincent07** [comment]
I was confused between the two data location path you have to fill. 
In the environment variable TAILSEEKER_DATADIR, you have to give the path to your Hiseq/Miseq output directory
`export TAILSEEKER_DATADIR=/home/user/runMiseq/161206_G02868_0017_000000000-AMCBY`
But in the `tailseeker.yaml` file, the `dir` subsection must be fill with `"/data"` and nothing else.
